/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Category;


import controller.CategoryController;
import dao.CategoryDAO;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Frame;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.Category;
import model.Suppliers;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import static org.apache.poi.ss.usermodel.CellType.BOOLEAN;
import static org.apache.poi.ss.usermodel.CellType.NUMERIC;
import static org.apache.poi.ss.usermodel.CellType.STRING;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.VerticalAlignment;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import view.NhapExcel;


/**
 *
 * @author Admin
 */
public class CategorysForm extends javax.swing.JPanel {
    private ThemDMForm themDMForm;  
    private SuaDMForm suaDMForm;
    private NhapExcel nhapExcel;
    CategoryController spController;
    CategoryDAO categoryDao;
    Category category;

    /**
     * Creates new form CategorysForm
     */
    public CategorysForm() {
        initComponents();
          // Chỉnh màu header bảng
        JTableHeader header = tblDanhSach.getTableHeader();
        header.setOpaque(false);
        header.setBackground(new java.awt.Color(46, 125, 50)); // Màu nền header
        header.setForeground(Color.WHITE);                   // Màu chữ header
        header.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));   // Font header
        
        // Tùy chỉnh chọn dòng
        tblDanhSach.setSelectionBackground(new Color(0, 153, 0)); // Màu khi chọn dòng
        tblDanhSach.setSelectionForeground(Color.WHITE);          // Chữ trắng khi chọn
        tblDanhSach.setRowHeight(25); 
        
        txtTimKiem.setText("Tìm kiếm theo tên danh mục");
        txtTimKiem.setForeground(Color.GRAY);

        txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtTimKiem.getText().equals("Tìm kiếm theo tên danh mục")) {
                    txtTimKiem.setText("");
                    txtTimKiem.setForeground(Color.BLACK);
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtTimKiem.getText().trim().isEmpty()) {
                    txtTimKiem.setText("Tìm kiếm theo tên danh mục");
                    txtTimKiem.setForeground(Color.GRAY);
                }
            }
        });
        
        spController = new CategoryController(this);
        categoryDao = new CategoryDAO();
        
        // Lấy Frame cha của JPanel hiện tại
        Frame parent = (Frame) SwingUtilities.getWindowAncestor(this);
        // Khởi tạo các dialog với parent đúng kiểu
        themDMForm = new ThemDMForm(parent, true);
        suaDMForm = new SuaDMForm(parent, true);
        nhapExcel = new NhapExcel(parent, true);
 

        btnThem.addActionListener(spController);
        btnSua.addActionListener(spController);
        btnXoa.addActionListener(spController);  
        btnXuat.addActionListener(spController);   
        btnNhap.addActionListener(spController); 
        btnTimKiem.addActionListener(spController);
      //  nhapExcel = new NhapExcel(this, true);
        nhapExcel.getBtnUpload().addActionListener(spController);
        nhapExcel.getBtnSave().addActionListener(spController);
        themDMForm.getBtnThemDm().addActionListener(spController);
        themDMForm.getBtnHuy().addActionListener(spController);
        
        
        suaDMForm.getBtnLuu().addActionListener(spController);
        suaDMForm.getBtnHuy().addActionListener(spController);
        
        loadCategory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnNhap = new javax.swing.JButton();
        btnXuat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTimKiem = new javax.swing.JTextPane();
        btnTimKiem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();

        jPanel4.setBackground(new java.awt.Color(46, 125, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÍ DANH MỤC");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(200, 230, 201));
        jLabel2.setText("Quản lí danh mục sản phẩm của GreenBuy");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(292, 292, 292))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(46, 125, 50))); // NOI18N

        btnThem.setIcon(new javax.swing.ImageIcon("D:\\iconJV\\add (1).png")); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorderPainted(false);
        btnThem.setContentAreaFilled(false);
        btnThem.setFocusPainted(false);
        btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThem.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnThem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnXoa.setBackground(new java.awt.Color(204, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon("D:\\iconJV\\trash (1).png")); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorderPainted(false);
        btnXoa.setContentAreaFilled(false);
        btnXoa.setFocusPainted(false);
        btnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoa.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnXoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnSua.setBackground(new java.awt.Color(204, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon("D:\\iconJV\\edit (1).png")); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorderPainted(false);
        btnSua.setContentAreaFilled(false);
        btnSua.setFocusPainted(false);
        btnSua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSua.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnNhap.setBackground(new java.awt.Color(204, 255, 255));
        btnNhap.setIcon(new javax.swing.ImageIcon("D:\\iconJV\\excel.png")); // NOI18N
        btnNhap.setText("Nhập Excel");
        btnNhap.setBorderPainted(false);
        btnNhap.setContentAreaFilled(false);
        btnNhap.setFocusPainted(false);
        btnNhap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhap.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnNhap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnXuat.setBackground(new java.awt.Color(204, 255, 255));
        btnXuat.setIcon(new javax.swing.ImageIcon("D:\\iconJV\\sheets.png")); // NOI18N
        btnXuat.setText("Xuất Excel");
        btnXuat.setBorderPainted(false);
        btnXuat.setContentAreaFilled(false);
        btnXuat.setFocusPainted(false);
        btnXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXuat.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnNhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnXuat)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnNhap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnXuat))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(46, 125, 50))); // NOI18N

        jScrollPane1.setViewportView(txtTimKiem);

        btnTimKiem.setBackground(new java.awt.Color(46, 125, 50));
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setIcon(new javax.swing.ImageIcon("D:\\iconJV\\searching.png")); // NOI18N
        btnTimKiem.setText("Tìm kiếm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimKiem)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách nhà cung cấp\n\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(46, 125, 50))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(827, 583));

        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDanhSach);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhap;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextPane txtTimKiem;
    // End of variables declaration//GEN-END:variables

    public void HienthiForm(String action) {
        if("Thêm".equals(action)){
            themDMForm.setLocationRelativeTo(this);
            themDMForm.setVisible(true);
          
        }else if("Sửa".equals(action)){
            int selectedRow = tblDanhSach.getSelectedRow();
            if(selectedRow >= 0){
                    String maDM = tblDanhSach.getValueAt(selectedRow, 0).toString();
                    String ten = tblDanhSach.getValueAt(selectedRow, 1).toString();
                    String mota = tblDanhSach.getValueAt(selectedRow, 2).toString();
                    Category sp = new Category(Integer.parseInt(maDM), ten, mota);
                    suaDMForm.setValue(sp);
                    suaDMForm.setLocationRelativeTo(this);
                    suaDMForm.setVisible(true);

               }           
        }else if("Xóa".equals(action)){
            int selectedRow = tblDanhSach.getSelectedRow();
            if(selectedRow >=0){
                String maDM = tblDanhSach.getValueAt(selectedRow, 0).toString();
                String ten = tblDanhSach.getValueAt(selectedRow, 1).toString();
                String mota = tblDanhSach.getValueAt(selectedRow, 2).toString();
                Category sp = new Category(Integer.parseInt(maDM), ten, mota);
                int choise = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn có muốn xóa dữ liệu?", 
                        "Xóa", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(choise == JOptionPane.YES_OPTION){
                    categoryDao.category_delete(sp);
                    JOptionPane.showMessageDialog(null, "Đã xóa thành công.");
                    loadCategory();
                }                            
            } 
        }else if("Nhập Excel".equals(action)){
            nhapExcel.setLocationRelativeTo(this);
            nhapExcel.setVisible(true);
        }
        
    }

    public void AddSupplier() {
        try{
            //gọi hàm getmodel ở form themncc đẻ lấy thông tin vừa nhập
            var supplier = themDMForm.getModel();
            // gọi hàm dao   
            categoryDao.category_insert(supplier);
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            loadCategory();   
         //   themDMForm.clear();
        }catch(Exception ex){
            String messages = ex.getMessage();
            var mesErr = convertToStringList(messages);
            String mess = "";
            for (String m : mesErr) {
                mess += m + "\n";
            }
            JOptionPane.showMessageDialog(this, mess, "Lỗi", JOptionPane.ERROR_MESSAGE);
        }    
    }

    public void Huy() {
        themDMForm.setVisible(false);
        suaDMForm.setVisible(false);
        themDMForm.clear();
    }
   
    public void UpdateCategory() {
         try {            
            var category = suaDMForm.getModel();
            // gọi hàm dao   
            categoryDao.category_update(category);
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            suaDMForm.clear();
            loadCategory();   
        
        } catch (Exception e) {
            String messages = e.getMessage();
            var mesErr = convertToStringList(messages);
            String mess = "";
            for (String m : mesErr) {
                mess += m + "\n";
            }
            JOptionPane.showMessageDialog(this, mess, "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void loadCategory() {
           category = new Category();
           category.setCategory_name("");
           categoryDao.categoryfind(tblDanhSach,category);        
       }
    
    private static CellStyle DinhdangHeader(XSSFSheet sheet) {
           // Create font
           Font font = sheet.getWorkbook().createFont();
           font.setFontName("Times New Roman");
           font.setBold(true);
           font.setFontHeightInPoints((short) 12); // font size
           font.setColor(IndexedColors.WHITE.getIndex()); // text color

           // Create CellStyle
           CellStyle cellStyle = sheet.getWorkbook().createCellStyle();
           cellStyle.setFont(font);
           cellStyle.setAlignment(HorizontalAlignment.CENTER);
           cellStyle.setVerticalAlignment(VerticalAlignment.TOP);
           cellStyle.setFillForegroundColor(IndexedColors.GREEN.getIndex());
           cellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
           cellStyle.setBorderBottom(BorderStyle.THIN);
           cellStyle.setWrapText(true);
           return cellStyle;
       }
    public void Xuatbaocao() {
        try {
        XSSFWorkbook workbook = new XSSFWorkbook();
        XSSFSheet sheet = workbook.createSheet("Danh Mục");

        // Tạo styles
        CellStyle styleTitle = workbook.createCellStyle();
        Font fontTitle = workbook.createFont();
        fontTitle.setFontHeightInPoints((short) 14);
        fontTitle.setBold(true);
        styleTitle.setFont(fontTitle);
        styleTitle.setAlignment(HorizontalAlignment.CENTER);

        CellStyle styleHeader = workbook.createCellStyle();
        Font fontHeader = workbook.createFont();
        fontHeader.setBold(true);
        fontHeader.setColor(IndexedColors.WHITE.getIndex());
        styleHeader.setFont(fontHeader);
        styleHeader.setFillForegroundColor(IndexedColors.GREEN.getIndex());
        styleHeader.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        styleHeader.setBorderTop(BorderStyle.THIN);
        styleHeader.setBorderBottom(BorderStyle.THIN);
        styleHeader.setBorderLeft(BorderStyle.THIN);
        styleHeader.setBorderRight(BorderStyle.THIN);
        styleHeader.setAlignment(HorizontalAlignment.CENTER);

        CellStyle styleCell = workbook.createCellStyle();
        styleCell.setBorderTop(BorderStyle.THIN);
        styleCell.setBorderBottom(BorderStyle.THIN);
        styleCell.setBorderLeft(BorderStyle.THIN);
        styleCell.setBorderRight(BorderStyle.THIN);
        styleCell.setVerticalAlignment(VerticalAlignment.CENTER);
        styleCell.setWrapText(true);

        // Tạo tiêu đề
        Row titleRow = sheet.createRow(1); // Dòng 2 (index 1)
        Cell titleCell = titleRow.createCell(0); // Cột A (index 0)
        titleCell.setCellValue("DANH SÁCH DANH MỤC SẢN PHẨM");
        titleCell.setCellStyle(styleTitle);
        sheet.addMergedRegion(new CellRangeAddress(1, 1, 0, 3)); // Merge A2:F2

        // Tạo dòng tiêu đề bảng
        Row headerRow = sheet.createRow(3);
        String[] headers = { "STT", "Mã Danh Mục", "Tên Danh Mục", "Mô Tả" };
        for (int i = 0; i < headers.length; i++) {
            Cell cell = headerRow.createCell(i);
            cell.setCellValue(headers[i]);
            cell.setCellStyle(styleHeader);
        }

        // Lấy dữ liệu
        String ten = txtTimKiem.getText().trim();
        category.setCategory_name(ten);
        ResultSet rs = categoryDao.load_execel(category);

        if (rs == null) {
            JOptionPane.showMessageDialog(null, "Không có dữ liệu để xuất");
            return;
        }

        int rowIdx = 4;
        int stt = 1;
        while (rs.next()) {
            Row row = sheet.createRow(rowIdx++);

            // STT
            Cell cell0 = row.createCell(0);
            cell0.setCellValue(stt++);
            cell0.setCellStyle(styleCell);

            // Mã NCC
            row.createCell(1).setCellValue(rs.getInt("category_id"));
            row.getCell(1).setCellStyle(styleCell);

            // Tên NCC
            row.createCell(2).setCellValue(rs.getString("category_name"));
            row.getCell(2).setCellStyle(styleCell);

            // Mô Tả
            row.createCell(3).setCellValue(rs.getString("description"));
            row.getCell(3).setCellStyle(styleCell);  
        }

        // Auto resize cột
        for (int i = 0; i < headers.length; i++) {
            sheet.autoSizeColumn(i);
        }

        // Ghi ra file
        File f = new File("D:\\caheo\\Danhsachdanhmuc.xlsx");
        FileOutputStream out = new FileOutputStream(f);
        workbook.write(out);
        out.close();
        workbook.close();

        JOptionPane.showMessageDialog(null, "Xuất báo cáo thành công!");
        
        //  Mở file Excel sau khi nhấn OK
        if (Desktop.isDesktopSupported()) {
            Desktop.getDesktop().open(f);
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Lỗi khi xuất báo cáo: " + e.getMessage());
    }
        
    }
    
    // nhập excel
    private void ReadExcel(String filePath, JTable tbBang) {
    try (FileInputStream fis = new FileInputStream(filePath)) {
        Workbook wb = new XSSFWorkbook(fis);
        Sheet sheet = wb.getSheetAt(0);

        Iterator<Row> itr = sheet.iterator();
        if (itr.hasNext()) itr.next(); // Bỏ qua dòng tiêu đề
        tbBang.removeAll();
        String[] head= {"STT","Tên Danh Mục","Mô Tả"};
        DefaultTableModel tb = new DefaultTableModel(head,0);
        while (itr.hasNext()) {
            Row row = itr.next();
            try {
                // Đọc và ép kiểu dữ liệu an toàn
                int stt = (int) row.getCell(0).getNumericCellValue();
                String name = getCellStringValue(row.getCell(1));
                String mota = getCellStringValue(row.getCell(2));
              
                // Gọi DAO hoặc Controller để thêm vào CSDL
                Category category = new Category();
                category.setCategory_id(stt);
                category.setCategory_name(name);
                category.setDescription(mota);
               

                 // <-- đảm bảo bạn đã viết hàm này
             
                Vector vt = new Vector();
                    vt.add(stt);
                    vt.add(name);
                    vt.add(mota);
                   
                tb.addRow(vt);
                tbBang.setModel(tb);
            } catch (Exception e) {
                System.err.println("Lỗi dòng " + row.getRowNum() + ": " + e.getMessage());
                // tiếp tục đọc các dòng sau
            }
        }

        wb.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi đọc file Excel: " + e.getMessage());
    }
}
    private String getCellStringValue(Cell cell) {
            if (cell == null) return "";
            switch (cell.getCellType()) {
                case STRING:
                    return cell.getStringCellValue();
                case NUMERIC:
                    return String.valueOf((long) cell.getNumericCellValue());
                case BOOLEAN:
                    return String.valueOf(cell.getBooleanCellValue());
                default:
                    return "";
            }
        }
    public void Upload() {
          JFileChooser fc = new JFileChooser();
            int result = fc.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();

                nhapExcel.getTxtFile().setText(file.getPath());

                if (file.getName().toLowerCase().endsWith(".xlsx")) {
                    ReadExcel(file.getPath(), nhapExcel.getTblNCC());
                    JOptionPane.showMessageDialog(this, "Import thành công!");
                    loadCategory(); // Gọi lại để load dữ liệu lên bảng
                } else {
                    JOptionPane.showMessageDialog(this, "Vui lòng chọn file Excel (.xlsx)");
                }
            }
        
    }

    public void SaveDataFromExcel() {
         DefaultTableModel model = (DefaultTableModel) nhapExcel.getTblNCC().getModel();
        int rowCount = model.getRowCount();
        int countInserted = 0, countSkipped = 0;

        for (int i = 0; i < rowCount; i++) {
            Category category = new Category();
            try {
                category.setCategory_id(Integer.parseInt(model.getValueAt(i, 0).toString()));
                category.setCategory_name(model.getValueAt(i, 1).toString());
                category.setDescription(model.getValueAt(i, 2).toString());
               
                // ❗ Kiểm tra trùng TÊN hoặc SỐ ĐIỆN THOẠI
                if (categoryDao.isCategoryExists(category.getCategory_name())) {
                    countSkipped++;
                    continue;
                }
                // Insert vào DB
                categoryDao.category_insert(category);
                countInserted++;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Lỗi tại dòng " + (i + 1) + ": " + ex.getMessage());
            }
        }
        JOptionPane.showMessageDialog(this,
        "✔️ Đã thêm " + countInserted + " DM mới\n❌ Bỏ qua " + countSkipped + " dòng do trùng tên ");
        loadCategory();
        
    }

    public void timKiem() {
    String tuKhoa = txtTimKiem.getText().trim();

    // Nếu là placeholder hoặc người dùng xóa hết nội dung
    if (tuKhoa.equals("Tìm kiếm theo tên danh mục") || tuKhoa.isEmpty()) {
        loadCategory(); // Gọi lại hàm load toàn bộ danh mục
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tblDanhSach.getModel();
    model.setRowCount(0); // Xóa dữ liệu cũ

    ResultSet rs = categoryDao.timKiem(tuKhoa);

    try {
        while (rs != null && rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("category_id"),
                rs.getString("category_name"),
                rs.getString("description")
            });
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
    private List<String> convertToStringList(String suppliersString) {
        // Remove square brackets and split by ", "
        String cleanedString = suppliersString.replaceAll("\\[|\\]", "");
        if (cleanedString.isEmpty()) {
            return new ArrayList<>();
        }
        return new ArrayList<>(Arrays.asList(cleanedString.split(", ")));
    }

}
